### ISSUE TITLE
What will modules and the package index look like?

### ISSUE THREAD

**Issue by alshdavid** [alshdavid/TypeScriptBC#13]
I personally like yaml because the task running steps can be multi line strings, we have comments and everyone knows it.
```yaml
# project.yaml
scripts:
  start: |
    echo "Hello World"
dependencies:
  main:
    - "git@github.com/foo/bar.git" 
  optional:
    - "git@github.com/foo/bar.git" 
  development:
    - "git@github.com/foo/bar.git" 
```
Not sure how I will describe dependencies. I quite like Go's use of git to share source, though that would limit packages that prefer to be distributed as private/compiled libraries. 

Deno has a cool model too. 

Broadly I would like to avoid a central repository like "npm"
